### ISSUE TITLE
_service Query in sdl is breaking federation requirements

### ISSUE THREAD

**Issue by Bastianowicz** [rdey/graphql-federation-bundle#2]
First of all: Thank you for this repo, which (I agree to you) should not exist at all. 
Either way it is needed and you provided it.

Unfortunately we are experiencing an issue while integrating the federated schema into a mercurius or apollo gateway server. Maybe you have an idea how to solve this. We would also try to help implementing the fix.

# Reproduction:
* install graphql-federation-bundle
* query _service.sdl

# Expectation:
* we would expect the root query to be resolved without the _service query in the sdl string

# Experienced:
* the received sdl contains _service query of type Service!
* the received sdl does not contain type definition Service
* thus it does not conform Federation v1 nor v2
* Mercurius Gateway complains `Error: Unknown type: "_Service"`

# Setup
* PHP: 8.1
* Symfony-flex: 1.19.3
* redeye/graphql-federation-bundle: dev-master
* overblog/graphql-bundle: 0.14.1

# Config
```yaml
# graphql.yaml
overblog_graphql:
  definitions:
    schema:
      query: RootQuery
    mappings:
      types:
        - type: attribute
          dir: "%kernel.project_dir%/src/GraphQL"
          suffix: ~
        - type: attribute
          dir: "%kernel.project_dir%/src/Module/*/Driver/GraphQL"
          suffix: ~
  security:
    enable_introspection: '%kernel.debug%'
```

Chances are we messed up the configuration somehow so we would love any kind of hint that you could provide.
